Documentation
alan-turing-institute/clim-recal pull request #62
Opened 2023-09-28 15:37 UTC by aranas

this PR is to open up my work on the main guidance & documentation. Will soon invite for review and tag people in specific sections that I think need review specifically

2023-10-12 13:37 UTC, aranas commented
> Hey just FYI: I've gotten part of the way through with a test of deployment via [`quarto`](https://quarto.org/). Can push that up as a separate branch to have a peak at if you like.

awesome! Yes I think a separate branch would be great. I guess this PR is really more about the guidance bit of the documentation rather than the actual code documentation. Will change the name to make that less confusing.

2023-10-12 14:56 UTC, aranas commented
I need to remove the sphinx make files from this PR they are not meant to be part of this, only the guidance

2023-10-23 16:55 UTC, gmingas requested changes
This looks good, thanks for the massive amount of work Sophie!

I added some suggestins/comments. 

Also, before merging this will require a significant merge with main, as main has changed a lot since the branch was created (10 Aug). Some of the commits in main since 10 Aug modified the readme file in the top directory so these would have to be reconciled with what you did here (keeping all useful info).

2023-10-23 16:55 UTC, gmingas commented on README.md
> +Welcome to clim-recal, a specialized resource designed to tackle systematic errors or biases in Regional Climate Models (RCMs). As researchers, policy-makers, and various stakeholders explore publicl
```suggestion
Welcome to clim-recal, a specialized resource designed to tackle systematic errors or biases in Regional Climate Models (RCMs). As researchers, policy-makers, and various stakeholders explore publicly available RCMs, they need to consider the challenge of biases that can affect the accurate representation of climate change signals. 

Clim-recal provides both a **broad review** of available bias correction methods as well as **software**, **practical tutorials** and **guidance** that helps users apply these methods methods to various datasets.
```

2023-10-23 16:55 UTC, gmingas commented on README.md
> +- Technical resource for application BC methods (see our full pipeline for bias-correction of the ground-breaking local-scale (2.2km)[Convection Permitting Model (CPM)](https://www.metoffice.gov.uk/p
```suggestion
- Is a software library for for the application of BC methods (see our full pipeline for bias-correction of the ground-breaking local-scale (2.2km)[Convection Permitting Model (CPM)](https://www.metoffice.gov.uk/pub/data/weather/uk/ukcp18/science-reports/UKCP-Convection-permitting-model-projections-report.pdf)). Clim-recal brings together different software packages in Python and R that implement a variety of bias correction methods, making it easy to apply them to data and compare their outputs.
```

2023-10-23 16:55 UTC, gmingas commented on README.md
> +- In partnership with the MetOffice to ensure the propriety, quality, and usability of our work
```suggestion
- Was developed in partnership with the MetOffice to ensure the propriety, quality, and usability of our work
```

2023-10-23 16:55 UTC, gmingas commented on README.md
> +- Framework for open additions (in planning)
```suggestion
- Provides a framework for open additions of new software libraries/bias correction methods (in planning)
```

2023-10-23 16:55 UTC, gmingas commented on docs/pipeline_guidance.md
> +In order to paralellize the reprojection step, we make use of the [GNU parallel shell tool](https://www.gnu.org/software/parallel/).
Could you mention here that this needs to be installed and point to just the page that explains how? Or just include the installation command for the terminal directly?

2023-10-23 16:55 UTC, gmingas commented on docs/pipeline_guidance.md
> +```
I think we also need to mention the `chmod` lines mentioned here: https://github.com/alan-turing-institute/clim-recal/issues/30 or find an equivalent solution.

2023-10-26 13:10 UTC, aranas commented
> Also, before merging this will require a significant merge with main, as main has changed a lot since the branch was created (10 Aug). 
urrg good point, once we think this can be merged, I can go through the merge conflicts and consolidate.

2023-10-27 10:32 UTC, aranas commented
This branch has been merged into branch `documentation-quarto`, so I will close the PR

2023-10-27 10:32 UTC, closed without merging