Add `pytest` config and test `debiasing/preprocess_data.py`
alan-turing-institute/clim-recal pull request #64
Opened 2023-10-03 04:30 UTC by griff-rees

This branch was initially forked from `three-cities` and focused on providing test infrastructure for python components within an initial focus on `debiasing`. Under the current configuration, tests can be run within the activated `conda` environment in the `python` folder:

```console
$ cd cli-recal/python
$ conda activate clim-recal
$ pytest
....................                                                                                                                                                                
20 passed in 7.01s
```

Test configuration is currently managed within `python/.pytest.conf`. Two types of tests are currently included:

- Unit Tests from files in `python/tests/` with filenames prefixed by `test_` (currently only `python/tests/test_debiasing.py`)
- [`doctests`](https://docs.python.org/3/library/doctest.html) via `docstrings` in blocks of code, initial examples in `utils.py`

2023-10-23 15:45 UTC, gmingas requested changes
This looks really good and also see comments below. 

Additionally, could we add instructions on how to run tests in the `README.md`? Just a simple few lines similar to the PR description.

2023-10-23 16:07 UTC, griff-rees commented on python/tests/test_debiasing.py
> +PROCESSESORS_DEFAULT: Final[int] = 32
Sure, it was a copy of the config for the server as best I could understand. Perhaps 2 for safety?

2023-10-23 16:10 UTC, griff-rees commented on python/tests/test_debiasing.py
> +)
Cool. The current config tests two city cases:

- `Manchester` (the default in that config, hence `None`, and by extension that's a test of defaults
- `Glasgow`

Is there a particular set of parameter combinations you'd like to add?

2023-10-23 16:11 UTC, gmingas commented on python/tests/test_debiasing.py
> +PROCESSESORS_DEFAULT: Final[int] = 32
Sounds good

2023-10-23 16:12 UTC, gmingas commented on python/tests/test_debiasing.py
> +)
I would probably add the equivalent of (London, 06, rainfall, delta_method) to test a few things at the same time, which should be enough for now

2023-10-25 13:36 UTC, griff-rees commented on bash/ubuntu_install.sh
Apologies: having looked it over again, it's actually what I used to deploy the configuration on the `azure` box, in the hope that could be automated (especially if we can't use `docker`) so actually I think this should be included in this branch. Would you like to review this?

2023-10-25 13:47 UTC, gmingas commented on bash/ubuntu_install.sh
Sure, happy to keep it in that case

2023-10-25 14:04 UTC, griff-rees commented on python/tests/test_debiasing.py
> +)
Ok. I've got a draft commit. Logging will likely differ significantly for `rainfall` and `delta_method` so those portions of the test are non-trivial to alter. I'm putting in an example commit for review, but will need to connect to the server again to test.

2023-10-26 14:38 UTC, griff-rees commented on python/tests/test_debiasing.py
> +)
Addressed in 52f7ac8c865d9b6d803e628dedd7ab3161740560

2023-10-26 14:39 UTC, griff-rees commented on bash/ubuntu_install.sh
Cool thanks.

2023-11-02 15:49 UTC, gmingas approved these changes
Looks good!

2023-11-07 22:53 UTC, merged