Adding Shapefile
alan-turing-institute/clim-recal pull request #86
Opened 2023-11-15 23:55 UTC by BZ-BowenZhang

This pull request includes: 

1. Adding a Geofile folder under the current data folder, including the shapefiles of NUT1 boundaries of the UK.
2. Adding a paragraph in the `readme.md` from line 100-102 to introduce the geographical dataset

2023-11-15 23:57 UTC, BZ-BowenZhang commented
This pull request is linked to issue #86 for adding the shapefiles.

2023-11-16 12:38 UTC, griff-rees commented on README.md
Just a suggestion for the text:

```md
The geographical dataset can be used for visualising climate data. It mainly includes administrative boundaries published by the Office for National Statistics (ONS). The dataset is sharable under the [Open Government Licence v.3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/) and is available for download via this [link](https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/NUTS_Level_1_January_2018_FCB_in_the_United_Kingdom_2022/FeatureServer/replicafilescache/NUTS_Level_1_January_2018_FCB_in_the_United_Kingdom_2022_7279368953270783580.zip). We include a copy in the `data/Geofiles` folder for convenience.
```

2023-11-16 12:45 UTC, griff-rees requested changes
Looks good to me. Just made a minor suggestion for the `README.md` text, mainly a link to the Open Government Licence. Only other thought is whether the shape of London mentioned in #68 needs any further checks.

2023-11-16 13:38 UTC, BZ-BowenZhang commented on README.md
That sounds good! Thanks Griff!

2023-11-16 13:46 UTC, BZ-BowenZhang commented
> Looks good to me. Just made a minor suggestion for the `README.md` text, mainly a link to the Open Government Licence. Only other thought is whether the shape of London mentioned in #68 needs any further checks.

The London shapefile actually is a clip from the NUT1 data, so it is from exactly the same source.

2023-11-16 14:27 UTC, BZ-BowenZhang commented
@griff-rees  I revised the `README.md`, and also added a sentence to clarify the `three.cities` folder.

2023-11-17 08:32 UTC, gmingas approved these changes
I think this is good to go

2023-11-17 13:39 UTC, griff-rees approved these changes

2023-11-17 13:41 UTC, merged